/**
 * GÉNÉRÉ par scripts/generate-exercises-seed.mjs — NE PAS ÉDITER À LA MAIN.
 * Source de vérité : static/exercises/ (registre + exercise.json par slug).
 *
 * Bibliothèque officielle G-FLUX embarquée pour le SEED des Convex PREVIEW
 * (previewSeed.ts). Données de RÉFÉRENCE uniquement — aucune donnée
 * personnelle. Médias : URLs relatives au dépôt, servies par chaque
 * déploiement Netlify (aucun Storage ID Convex, rien de spécifique à la prod).
 */

export const GFLUX_OFFICIAL_SOURCE = "gflux-official";

export const GFLUX_OFFICIAL_LICENSE =
	"Bibliothèque officielle G-FLUX — média propriétaire (dépôt), art direction femme athlétique";

export type SeedExercise = {
	sourceExerciseId: string;
	name: string;
	sourceName: string;
	muscleGroup: string;
	secondaryMuscles: string[];
	bodyPart: string;
	equipment: string;
	instructions: string[];
	cues: string[];
	mistakes: string[];
	levels: string[];
	breathing: { eccentric?: string; concentric?: string };
	posterUrl: string;
	animationUrl: string;
};

/** 34 exercices validés du registre. */
export const GFLUX_OFFICIAL_EXERCISES: SeedExercise[] = [
	{
		"sourceExerciseId": "band-external-rotation",
		"name": "Rotation externe des épaules avec bande",
		"sourceName": "Band External Rotation",
		"muscleGroup": "Épaules",
		"secondaryMuscles": [
			"Trapèzes",
			"Rhomboïdes",
		],
		"bodyPart": "Tronc",
		"equipment": "Élastiques",
		"instructions": [
			"Tiens la bande à deux mains, coudes pliés à 90°, collés contre ton corps.",
			"Avance d’un pas pour créer une légère tension sur la bande.",
			"Garde les coudes verrouillés contre tes côtes pendant tout le mouvement.",
			"Ouvre les avant-bras vers l’extérieur en rotant les épaules, sans décoller les coudes.",
			"Reviens lentement au centre en contrôlant la bande, et enchaîne.",
		],
		"cues": [
			"Coudes collés aux côtes du début à la fin.",
			"Angles à 90° : coude plié, avant-bras horizontal.",
			"Épaules basses, loin des oreilles.",
			"Le mouvement vient des épaules, pas des coudes ni du buste.",
			"Amplitude confortable : mieux vaut petit et propre que grand et tordu.",
		],
		"mistakes": [
			"Décoller les coudes du corps pendant l’ouverture.",
			"Monter les épaules vers les oreilles.",
			"Basculer le buste en arrière pour aider.",
			"Utiliser une bande trop raide qui casse la position.",
			"Aller trop vite sans sentir la coiffe travailler.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en revenant au centre.",
			"concentric": "Expire en ouvrant les avant-bras.",
		},
		"posterUrl": "/exercises/band-external-rotation/poster.webp",
		"animationUrl": "/exercises/band-external-rotation/animation.mp4",
	},
	{
		"sourceExerciseId": "band-pallof-press",
		"name": "Pallof press avec bande",
		"sourceName": "Band Pallof Press",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Grand fessier",
			"Épaules",
		],
		"bodyPart": "Tronc",
		"equipment": "Élastiques",
		"instructions": [
			"Attache la bande à hauteur de torse sur un point fixe et tiens-la à deux mains contre ta poitrine.",
			"Place-toi de profil par rapport au point d’ancrage, pieds largeur de hanches, genoux légèrement fléchis.",
			"Éloigne-toi de l’ancrage pour créer une tension, puis tends les bras devant toi.",
			"Résiste à la rotation : la bande veut te faire pivoter, garde les hanches et les épaules face devant.",
			"Tiens la position une à deux secondes, puis ramène les mains contre la poitrine en contrôlant.",
		],
		"cues": [
			"Serre les fessiers et le ventre avant de tendre les bras.",
			"Pousse les mains loin, sans laisser le buste tourner.",
			"Hanches et épaules restent face à l’avant du mouvement.",
			"Respire sans relâcher la sangle abdominale.",
			"Plus tu t’éloignes de l’ancrage, plus la tension monte : ajuste la distance.",
		],
		"mistakes": [
			"Laisser le buste pivoter vers la bande pendant la poussée.",
			"Monter les épaules et tendre le cou pour retenir la tension.",
			"Bloquer la respiration au lieu de rester gainé en respirant.",
			"Vouloir trop de tension et compromettre la position des hanches.",
			"Faire le mouvement uniquement avec les bras, sans engager le tronc.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en ramenant les mains contre la poitrine.",
			"concentric": "Expire en tendant les bras, sans relâcher les abdos.",
		},
		"posterUrl": "/exercises/band-pallof-press/poster.webp",
		"animationUrl": "/exercises/band-pallof-press/animation.mp4",
	},
	{
		"sourceExerciseId": "band-romanian-deadlift",
		"name": "Soulevé de terre roumain avec bande",
		"sourceName": "Resistance Band Romanian Deadlift",
		"muscleGroup": "Ischio-jambiers",
		"secondaryMuscles": [
			"Lombaires",
			"Abdominaux",
			"Moyen fessier",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Élastiques",
		"instructions": [
			"Pose la bande sous tes deux pieds, pieds largeur de hanches.",
			"Tiens la bande à deux mains devant tes cuisses, bras tendus.",
			"Garde le dos plat, les épaules basses et le regard devant toi.",
			"Pousse les fessiers en arrière et descends le buste jusqu’à mi-tibia, jambes légèrement fléchies.",
			"Remonte en poussant le sol avec les talons et en serrant les fessiers en haut.",
		],
		"cues": [
			"La hanche pivote en arrière : le buste descend, il ne s’arrondit pas.",
			"Genoux légèrement fléchis, jamais verrouillés.",
			"La bande reste contre tes jambes, pas devant.",
			"Descends lentement, remonte plus vite mais contrôlé.",
			"Serre les fessiers en haut sans pousser le bassin trop loin.",
		],
		"mistakes": [
			"Arrondir le bas du dos pendant la descente.",
			"Transformer le mouvement en squat : les hanches descendent au lieu de reculer.",
			"Tirer avec les bras au lieu de dérouler depuis la hanche.",
			"Trop descendre et perdre le dos neutre.",
			"Verrouiller les genoux et tendre les ischio-jambiers sans contrôle.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en descendant le buste.",
			"concentric": "Expire en remontant à la verticale.",
		},
		"posterUrl": "/exercises/band-romanian-deadlift/poster.webp",
		"animationUrl": "/exercises/band-romanian-deadlift/animation.mp4",
	},
	{
		"sourceExerciseId": "glute-bridge-mini-band-abduction",
		"name": "Pont fessier avec abduction et mini-bande",
		"sourceName": "Glute Bridge with Mini Band Abduction",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Moyen fessier",
			"Ischio-jambiers",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Allonge-toi sur le dos, pieds à plat, genoux fléchis.",
			"Place la mini-bande juste au-dessus de tes genoux.",
			"Pousse dans les talons pour monter le bassin jusqu’à l’alignement épaules–genoux.",
			"En haut du pont, écarte les genoux contre la bande sans descendre le bassin.",
			"Referme les genoux puis redescends lentement : c’est une répétition.",
		],
		"cues": [
			"Monte le pont avec les fessiers, pas avec le bas du dos.",
			"Le bassin reste haut pendant toute l’abduction.",
			"Pousse dans les talons, orteils relâchés.",
			"Rentre légèrement le bassin pour ne pas cambrer.",
			"Contrôle la descente, ne te laisse pas retomber.",
		],
		"mistakes": [
			"Descendre le bassin pendant l’ouverture des genoux.",
			"Hypercambrer le bas du dos en haut du pont.",
			"Laisser les genoux rentrer sous la tension de la bande.",
			"Pousser avec la pointe des pieds.",
			"Enchaîner trop vite sans contraction en haut.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en redescendant le bassin.",
			"concentric": "Expire en montant le pont puis en écartant les genoux.",
		},
		"posterUrl": "/exercises/glute-bridge-mini-band-abduction/poster.webp",
		"animationUrl": "/exercises/glute-bridge-mini-band-abduction/animation.mp4",
	},
	{
		"sourceExerciseId": "lateral-band-walk",
		"name": "Marche latérale avec mini-bande",
		"sourceName": "Lateral Band Walk",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Petit fessier",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Place la mini-bande juste au-dessus de tes chevilles ou sous tes genoux.",
			"Tiens-toi debout, pieds largeur de hanches, légère flexion des genoux.",
			"Fais un grand pas latéral avec une jambe en gardant la tension sur la bande.",
			"Ramène l’autre pied pour retrouver l’écart initial, sans laisser la bande te tirer.",
			"Enchaîne plusieurs pas dans la même direction, puis reviens dans l’autre sens.",
		],
		"cues": [
			"Garde le buste droit et le regard devant toi.",
			"Reste légèrement fléchi, jamais les jambes verrouillées.",
			"Travaille pieds parallèles, orteils vers l’avant.",
			"Conserve la tension sur la bande pendant tout l’exercice.",
			"Bouge du bassin, pas du buste.",
		],
		"mistakes": [
			"Laisser le genou rentrer vers l’intérieur à chaque pas.",
			"Ramener les pieds trop vite sans contrôler la bande.",
			"Se pencher en avant ou balancer le bassin pour s’aider.",
			"Faire des pas trop petits pour garder de la tension.",
			"Monter sur la pointe des pieds entre chaque pas.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire de façon régulière pendant les pas.",
			"concentric": "Expire en contrôlant le rappel du pied.",
		},
		"posterUrl": "/exercises/lateral-band-walk/poster.webp",
		"animationUrl": "/exercises/lateral-band-walk/animation.mp4",
	},
	{
		"sourceExerciseId": "machine-hip-thrust",
		"name": "Hip Thrust à la machine",
		"sourceName": "Machine Hip Thrust",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Quadriceps",
			"Adducteurs",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Machine Hip Thrust",
		"instructions": [
			"Place le haut du dos contre le dossier et positionne le pad au niveau du pli des hanches.",
			"Place les pieds à largeur de bassin et bien à plat sur la plateforme.",
			"Descends le bassin de manière contrôlée.",
			"Pousse dans les pieds pour amener les hanches vers le haut.",
			"Termine le mouvement en contractant fortement les fessiers.",
			"Redescends lentement jusqu’à retrouver la position de départ.",
		],
		"cues": [
			"Garde les pieds bien ancrés.",
			"Cherche des tibias proches de la verticale en position haute.",
			"Monte le bassin sans hypercambrer le bas du dos.",
			"Contracte fortement les fessiers en haut.",
			"Contrôle la descente.",
		],
		"mistakes": [
			"Hypercambrer le bas du dos en position haute.",
			"Placer les pieds trop loin ou trop près du bassin.",
			"Pousser principalement avec l’avant des pieds.",
			"Rebondir en position basse.",
			"Sacrifier le contrôle pour augmenter l’amplitude.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente.",
			"concentric": "Expire pendant la poussée et la contraction des fessiers.",
		},
		"posterUrl": "/exercises/machine-hip-thrust/poster.webp",
		"animationUrl": "/exercises/machine-hip-thrust/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-clamshell",
		"name": "Coquille avec mini-bande",
		"sourceName": "Mini Band Clamshell",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Petit fessier",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Allonge-toi sur le côté, tête appuyée, jambes fléchies empilées à environ 45°.",
			"Place la mini-bande juste au-dessus de tes genoux.",
			"Garde les hanches empilées et le bassin immobile : c’est la clé de l’exercice.",
			"Ouvre le genou du dessus contre la tension de la bande, sans décoller les pieds.",
			"Referme lentement en contrôlant la bande, sans relâcher la tension entre les répétitions.",
		],
		"cues": [
			"Pieds collés du début à la fin, seul le genou bouge.",
			"Bassin verrouillé : ne bascule jamais en arrière.",
			"Le mouvement part de la hanche, pas du bas du dos.",
			"Ouvre petit mais propre plutôt que grand mais de travers.",
			"Garde une tension constante sur la bande, même en refermant.",
		],
		"mistakes": [
			"Basculer le bassin en arrière pour ouvrir plus loin.",
			"Décoller les pieds l’un de l’autre pendant l’ouverture.",
			"Aller trop vite avec des à-coups au lieu de contrôler.",
			"Cambrer le bas du dos pour gagner de l’amplitude.",
			"Utiliser une bande trop dure qui force la compensation du buste.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en refermant le genou.",
			"concentric": "Expire en ouvrant contre la bande.",
		},
		"posterUrl": "/exercises/mini-band-clamshell/poster.webp",
		"animationUrl": "/exercises/mini-band-clamshell/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-fire-hydrant",
		"name": "Fire hydrant avec mini-bande",
		"sourceName": "Mini Band Fire Hydrant",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Mets-toi à quatre pattes, mains sous les épaules, genoux sous les hanches.",
			"Place la mini-bande juste au-dessus de tes genoux.",
			"Garde le dos plat et le regard vers le sol.",
			"Ouvre une jambe sur le côté à hauteur de hanche, genou fléchi à 90°, sans tourner le bassin.",
			"Referme lentement sans poser le genou, et enchaîne avant de changer de jambe.",
		],
		"cues": [
			"Bassin carré face au sol, jamais de torsion.",
			"Le genou monte sur le côté, le pied suit passivement.",
			"Dos neutre : garde les abdos gainés pour verrouiller la colonne.",
			"Amplitude jusqu’à hauteur de hanche, pas plus.",
			"Mouvement lent : la bande fait tout le travail de résistance.",
		],
		"mistakes": [
			"Pivoter le bassin vers le haut pendant l’ouverture.",
			"Creuser le bas du dos et perdre le gainage.",
			"Monter la jambe trop haut en tordant la hanche.",
			"Relever la tête et casser la nuque.",
			"Aller trop vite en rebondissant au retour.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en ramenant le genou.",
			"concentric": "Expire en ouvrant la jambe sur le côté.",
		},
		"posterUrl": "/exercises/mini-band-fire-hydrant/poster.webp",
		"animationUrl": "/exercises/mini-band-fire-hydrant/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-glute-bridge",
		"name": "Pont fessier avec mini-bande",
		"sourceName": "Mini Band Glute Bridge",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Moyen fessier",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Allonge-toi sur le dos, pieds à plat largeur de hanches, genoux fléchis.",
			"Place la mini-bande juste au-dessus de tes genoux.",
			"Écarte légèrement les genoux pour créer une tension sur la bande.",
			"Pousse dans les talons pour monter le bassin jusqu’à l’alignement épaules–genoux.",
			"Contracte fort les fessiers en haut, puis redescends lentement sans poser complètement.",
		],
		"cues": [
			"Pousse dans les talons, pas dans la pointe des pieds.",
			"Garde les genoux écartés contre la tension de la bande.",
			"Rentre légèrement le bassin pour ne pas cambrer le bas du dos.",
			"Serre les fessiers en haut, comme si tu voulais les verrouiller.",
			"Contrôle la descente plutôt que de te laisser retomber.",
		],
		"mistakes": [
			"Monter trop haut et hypercambrer le bas du dos.",
			"Laisser les genoux rentrer vers l’intérieur sous la tension de la bande.",
			"Pousser avec l’avant des pieds au lieu des talons.",
			"Descendre trop vite en rebondissant sur le sol.",
			"Pousser le bassin avec le bas du dos au lieu des fessiers.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente du bassin.",
			"concentric": "Expire en poussant vers le haut et en serrant les fessiers.",
		},
		"posterUrl": "/exercises/mini-band-glute-bridge/poster.webp",
		"animationUrl": "/exercises/mini-band-glute-bridge/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-glute-kickback",
		"name": "Kickback fessier à quatre pattes avec mini-bande",
		"sourceName": "Mini Band Glute Kickback",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Moyen fessier",
			"Lombaires",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Mets-toi à quatre pattes, mains sous les épaules, genoux sous les hanches.",
			"Place la mini-bande autour de tes chevilles ou au creux des genoux.",
			"Garde le dos plat et le bassin carré face au sol.",
			"Pousse une jambe vers le plafond, genou fléchi à 90°, talon vers le ciel.",
			"Contracte le fessier en haut une seconde, puis redescends sans poser le genou avant la fin de la série.",
		],
		"cues": [
			"La poussée part du fessier, pas du bas du dos.",
			"Bassin immobile : ne tourne pas la hanche vers le haut.",
			"Talons vers le plafond, orteils relâchés.",
			"Amplitude moyenne, contraction maximale en haut.",
			"Dos neutre du début à la fin : les abdos restent gainés.",
		],
		"mistakes": [
			"Creuser les lombaires pour monter plus haut.",
			"Pivoter le bassin et perdre le carré des hanches.",
			"Lancer la jambe avec un à-coup.",
			"Monter trop haut en cassant l’alignement.",
			"Oublier la contraction en haut du mouvement.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en redescendant la jambe.",
			"concentric": "Expire en poussant la jambe vers le plafond.",
		},
		"posterUrl": "/exercises/mini-band-glute-kickback/poster.webp",
		"animationUrl": "/exercises/mini-band-glute-kickback/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-monster-walk",
		"name": "Monster Walk avec mini-bande",
		"sourceName": "Mini Band Monster Walk",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Quadriceps",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Place la mini-bande au-dessus de tes genoux ou de tes chevilles.",
			"Descends en demi-squat, buste légèrement penché, poids sur les talons.",
			"Fais un grand pas en diagonale vers l’avant avec une jambe.",
			"Ramène l’autre jambe dans le même axe en gardant la tension sur la bande.",
			"Enchaîne les pas dans un sens, puis repars dans l’autre, sans te redresser.",
		],
		"cues": [
			"Reste en demi-squat du premier au dernier pas.",
			"Pieds toujours parallèles, orteils vers l’avant.",
			"Genoux poussés vers l’extérieur, jamais rentrés.",
			"Passe par des pas larges : la bande doit rester tendue.",
			"Bouge des jambes, le buste reste stable.",
		],
		"mistakes": [
			"Se redresser entre chaque pas et perdre la tension.",
			"Faire des pas trop petits pour économiser l’effort.",
			"Laisser les genoux rentrer vers l’intérieur.",
			"Tourner les pieds vers l’extérieur au lieu de rester parallèle.",
			"Foncer en vitesse au lieu de contrôler chaque appui.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire de façon régulière pendant les pas.",
			"concentric": "Expire en poussant chaque pas vers l’extérieur.",
		},
		"posterUrl": "/exercises/mini-band-monster-walk/poster.webp",
		"animationUrl": "/exercises/mini-band-monster-walk/animation.mp4",
	},
	{
		"sourceExerciseId": "mini-band-squat",
		"name": "Squat avec mini-bande",
		"sourceName": "Mini Band Squat",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Moyen fessier",
			"Ischio-jambiers",
			"Adducteurs",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Place la mini-bande juste au-dessus de tes genoux, pieds largeur de hanches.",
			"Garde les bras devant toi ou mains jointes pour l’équilibre.",
			"Descends le bassin en arrière comme pour t’asseoir, genoux écartés contre la bande.",
			"Descends jusqu’à cuisses parallèles au sol, ou plus bas si ta mobilité le permet.",
			"Remonte en poussant dans tout le pied, en gardant les genoux écartés.",
		],
		"cues": [
			"Pousse activement les genoux vers l’extérieur pendant toute la descente.",
			"Garde le buste relativement droit et la poitrine ouverte.",
			"Poids réparti sur tout le pied, talons ancrés.",
			"Genoux dans l’axe des orteils, jamais rentrés vers l’intérieur.",
			"Squeeze les fessiers en remontant à la fin du mouvement.",
		],
		"mistakes": [
			"Laisser les genoux rentrer vers l’intérieur sous la tension de la bande.",
			"Se pencher trop en avant et transformer le squat en good morning.",
			"Monter sur la pointe des pieds en descendant.",
			"Descendre trop vite sans contrôle avant la remontée.",
			"Choisir une bande trop forte et sacrifier la profondeur.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente.",
			"concentric": "Expire en remontant et en serrant les fessiers en haut.",
		},
		"posterUrl": "/exercises/mini-band-squat/poster.webp",
		"animationUrl": "/exercises/mini-band-squat/animation.mp4",
	},
	{
		"sourceExerciseId": "seated-mini-band-hip-abduction",
		"name": "Abduction de hanche assise avec mini-bande",
		"sourceName": "Seated Hip Abduction with Mini Band",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Petit fessier",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Assieds-toie au bord d’un banc ou d’une chaise, dos droit.",
			"Place la mini-bande juste au-dessus de tes genoux.",
			"Pieds à plat, largeur de hanches, mains posées sur tes cuisses.",
			"Écarte les genoux vers l’extérieur contre la bande, sans basculer le bassin.",
			"Referme lentement en gardant la tension, puis enchaîne tes répétitions.",
		],
		"cues": [
			"Buste droit, assise haute : ne t’affaisse pas.",
			"Les genoux s’écartent, les pieds restent à plat.",
			"Bassin immobile, pas de bascule avant-arrière.",
			"Amplitude moyenne et contrôle constant.",
			"Garde la tension même en refermant.",
		],
		"mistakes": [
			"Se pencher en avant pour forcer l’écart.",
			"Décoller les talons ou la pointe des pieds.",
			"Bascule le bassin pendant l’ouverture.",
			"Aller trop vite sans sentir le moyen fessier.",
			"Bande trop haute sur les cuisses : résistance trop faible.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en refermant les genoux.",
			"concentric": "Expire en écartant les genoux contre la bande.",
		},
		"posterUrl": "/exercises/seated-mini-band-hip-abduction/poster.webp",
		"animationUrl": "/exercises/seated-mini-band-hip-abduction/animation.mp4",
	},
	{
		"sourceExerciseId": "standing-mini-band-hip-abduction",
		"name": "Abduction de hanche debout avec mini-bande",
		"sourceName": "Standing Hip Abduction with Mini Band",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Petit fessier",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Mini-bande",
		"instructions": [
			"Place la mini-bande autour de tes chevilles.",
			"Tiens-toi debout, pieds largeur de hanches, mains sur les hanches pour l’équilibre.",
			"Transfère ton poids sur une jambe, genou légèrement fléchi.",
			"Ouvre l’autre jambe sur le côté contre la bande, en gardant le bassin de face.",
			"Remonte la jambe lentement sans la poser, et enchaîne tes répétitions avant de changer de côté.",
		],
		"cues": [
			"Buste droit : ne te penche pas du côté opposé.",
			"Bassin immobile : la jambe bouge, rien d’autre.",
			"Pointe du pied vers l’avant, pas vers le plafond.",
			"Amplitude moyenne et contrôle constant de la bande.",
			"Garde les abdos gainés pour rester stable sur ta jambe d’appui.",
		],
		"mistakes": [
			"Pencher le buste à l’opposé pour monter plus haut.",
			"Tourner le bassin ou la pointe du pied vers le plafond.",
			"Lancer la jambe avec un à-coup au lieu de contrôler.",
			"Amplitude trop grande qui dérègle la position.",
			"Perdre la tension en ramenant la jambe trop vite.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en ramenant la jambe.",
			"concentric": "Expire en ouvrant la jambe contre la bande.",
		},
		"posterUrl": "/exercises/standing-mini-band-hip-abduction/poster.webp",
		"animationUrl": "/exercises/standing-mini-band-hip-abduction/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-back-extension",
		"name": "Extension lombaire sur Swiss Ball",
		"sourceName": "Swiss Ball Back Extension",
		"muscleGroup": "Érecteurs du rachis",
		"secondaryMuscles": [
			"Grand fessier",
			"Ischio-jambiers",
			"Grand dorsal",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Couché sur le ventre sur le ballon, bassin calé sur le sommet, pieds calés contre un mur ou tenus au sol.",
			"Mains aux tempes ou croisées sur la poitrine, nuque dans l'alignement.",
			"Monte le buste jusqu'à l'alignement du corps, en serrant les fessiers.",
			"Ne dépasse pas légèrement l'alignement : pas d'hyperextension forcée.",
			"Redescends lentement en contrôlant, sans se laisser tomber.",
		],
		"cues": [
			"Le mouvement part des hanches, pas du bas du dos.",
			"Serre les fessiers pour verrouiller le bassin.",
			"Monte le buste comme un bloc, sans cassure.",
			"Amplitude maîtrisée : la qualité avant la hauteur.",
			"Nuque relâchée, regard au sol.",
		],
		"mistakes": [
			"Hyperextendre le bas du dos en haut du mouvement.",
			"Donner de l'élan en rebondissant sur le ballon.",
			"Pousser avec les mains pour monter plus haut.",
			"Monter la tête et la nuque en premier.",
			"Aller trop vite et perdre le contrôle du ballon.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en redescendant le buste.",
			"concentric": "Expire en montant le buste.",
		},
		"posterUrl": "/exercises/swiss-ball-back-extension/poster.webp",
		"animationUrl": "/exercises/swiss-ball-back-extension/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-body-saw",
		"name": "Body saw sur Swiss Ball",
		"sourceName": "Swiss Ball Body Saw",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Obliques",
			"Épaules",
			"Quadriceps",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en planche sur les avant-bras, tibias posés sur le ballon, coudes sous les épaules.",
			"Corps parfaitement aligné, ventre et fessiers serrés.",
			"Pousse avec les avant-bras pour faire rouler le ballon vers l'arrière et tirer ton corps.",
			"Étire-toi le plus loin possible SANS laisser le bas du dos se creuser.",
			"Ramène le ballon vers la position de départ en contrôlant.",
		],
		"cues": [
			"Le bassin avance et recule comme un bloc, sans bouger.",
			"Stoppe le mouvement dès que le bas du dos veut creuser.",
			"Serre les fessiers en permanence.",
			"Petites amplitudes d'abord : la qualité avant la distance.",
			"Épaules actives, loin des oreilles.",
		],
		"mistakes": [
			"Laisser le bas du dos se creuser en s'étirant.",
			"Monter les hanches pour faciliter le mouvement.",
			"Aller trop loin et perdre le contrôle du ballon.",
			"Bouger la tête et la nuque.",
			"Oublier de respirer pendant l'effort.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en te laissant tirer vers l'arrière.",
			"concentric": "Expire en ramenant le ballon.",
		},
		"posterUrl": "/exercises/swiss-ball-body-saw/poster.webp",
		"animationUrl": "/exercises/swiss-ball-body-saw/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-crunch",
		"name": "Crunch sur Swiss Ball",
		"sourceName": "Swiss Ball Crunch",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Obliques",
			"Quadriceps",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Assieds-toi sur le ballon puis avance les pieds pour faire rouler le ballon sous ton bas du dos.",
			"Genoux à 90°, pieds à plat, mains le long de la tête sans tirer sur la nuque.",
			"Enroule le buste vers l'avant en contractant les abdominaux.",
			"Monte jusqu'à ce que les épaules se soulèvent du ballon.",
			"Redescends lentement en étirant les abdos sur le ballon.",
		],
		"cues": [
			"Le mouvement part des côtes, pas de la tête.",
			"Enroule la colonne vertèbre par vertèbre.",
			"Le bassin reste stable sur le ballon.",
			"Garde un espace entre menton et poitrine.",
			"Étirement complet en bas, contraction complète en haut.",
		],
		"mistakes": [
			"Tirer sur la nuque avec les mains.",
			"Descendre tout le buste vers l'arrière (perte de tension).",
			"Pousser avec les jambes pour monter.",
			"Aller trop vite sans contrôler.",
			"Bloquer la respiration pendant l'effort.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en te déroulant vers l'arrière.",
			"concentric": "Expire en enroulant le buste vers l'avant.",
		},
		"posterUrl": "/exercises/swiss-ball-crunch/poster.webp",
		"animationUrl": "/exercises/swiss-ball-crunch/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-glute-bridge-march",
		"name": "Pont fessier en marche sur Swiss Ball",
		"sourceName": "Swiss Ball Glute Bridge March",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Abdominaux",
			"Mollets",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le dos, les deux pieds posés sur le ballon, jambes à peu près tendues.",
			"Monte en pont en poussant les talons dans le ballon, hanches hautes.",
			"Ramène un genou vers la poitrine sans laisser le bassin bouger.",
			"Retends la jambe sur le ballon, puis alterne avec l'autre.",
			"Le bassin reste aligné épaules-genoux pendant toute la série.",
		],
		"cues": [
			"Hanches hautes et immobiles : c'est le critère principal.",
			"Serre les fessiers en continu.",
			"Ramène le genou lentement, sans faire basculer le bassin.",
			"Pieds bien centrés sur le ballon.",
			"Respire à chaque montée de genou.",
		],
		"mistakes": [
			"Laisser le bassin pencher d'un côté à chaque montée de genou.",
			"Poser les hanches entre deux répétitions.",
			"Pousser le ballon vers l'avant au lieu de rester stable.",
			"Creuser le bas du dos.",
			"Aller trop vite et perdre le contact pieds-ballon.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en retendant la jambe sur le ballon.",
			"concentric": "Expire en ramenant le genou vers la poitrine.",
		},
		"posterUrl": "/exercises/swiss-ball-glute-bridge-march/poster.webp",
		"animationUrl": "/exercises/swiss-ball-glute-bridge-march/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-glute-bridge-squeeze",
		"name": "Pont fessier avec Swiss Ball et squeeze des adducteurs",
		"sourceName": "Swiss Ball Glute Bridge with Adductor Squeeze",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Abdominaux",
			"Mollets",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le dos, genoux fléchis, ballon serré entre tes genoux, pieds au sol.",
			"Serre le ballon avec les genoux et garde cette pression constante.",
			"Pousse dans les talons pour monter le bassin jusqu'à l'alignement épaules-genoux.",
			"Serre fort les fessiers en haut, sans relâcher la pression sur le ballon.",
			"Redescends lentement sans poser complètement ni lâcher le ballon.",
		],
		"cues": [
			"La pression sur le ballon ne baisse jamais, même en haut.",
			"Pousse dans les talons, pas dans la pointe des pieds.",
			"Bassin neutre : pas de cambrure en haut du mouvement.",
			"Serre les fessiers comme pour verrouiller en haut.",
			"Descente contrôlée, vertèbre par vertèbre.",
		],
		"mistakes": [
			"Lâcher la pression sur le ballon en montant.",
			"Cambrer le bas du dos en haut du pont.",
			"Pousser le ballon d'un côté : les genoux restent dans l'axe.",
			"Monter trop haut et perdre les fessiers.",
			"Descendre en se laissant tomber.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente du bassin.",
			"concentric": "Expire en montant le pont et en serrant.",
		},
		"posterUrl": "/exercises/swiss-ball-glute-bridge-squeeze/poster.webp",
		"animationUrl": "/exercises/swiss-ball-glute-bridge-squeeze/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-hip-thrust",
		"name": "Hip thrust sur Swiss Ball",
		"sourceName": "Swiss Ball Hip Thrust",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Abdominaux",
			"Mollets",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le dos, épaules au sol, bras le long du corps.",
			"Place les talons sur le ballon, jambes fléchies à environ 90°.",
			"Pousse dans les talons pour monter le bassin jusqu'à l'alignement épaules-genoux.",
			"Serre fort les fessiers en haut, une à deux secondes.",
			"Redescends lentement le bassin sans poser complètement.",
		],
		"cues": [
			"Le ballon doit rester immobile : pieds bien ancrés dessus.",
			"Pousse dans les talons, pas dans la pointe des pieds.",
			"Bassin neutre en haut : serre les fessiers, ne cambr pas.",
			"Menton légèrement rentré, nuque relâchée.",
			"Descente contrôlée, sans se laisser retomber.",
		],
		"mistakes": [
			"Laisser le ballon rouler pendant la poussée.",
			"Cambrer le bas du dos en haut du mouvement.",
			"Monter trop haut avec le bas du dos au lieu des fessiers.",
			"Pousser avec l'avant du pied.",
			"Descendre trop vite en rebondissant.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente du bassin.",
			"concentric": "Expire en poussant le bassin vers le haut.",
		},
		"posterUrl": "/exercises/swiss-ball-hip-thrust/poster.webp",
		"animationUrl": "/exercises/swiss-ball-hip-thrust/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-jackknife",
		"name": "Jackknife sur Swiss Ball",
		"sourceName": "Swiss Ball Jackknife",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Obliques",
			"Épaules",
			"Quadriceps",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en planche haute, mains sous les épaules, tibias sur le ballon.",
			"Corps aligné, ventre et fessiers serrés.",
			"Monte les hanches vers le plafond en laissant le ballon rouler vers les chevilles.",
			"Le corps forme un V inversé en haut du mouvement.",
			"Redescends en contrôlant jusqu'à la planche de départ.",
		],
		"cues": [
			"Le mouvement part des hanches, pas des bras.",
			"Bras fixes, épaules au-dessus des mains.",
			"Serre les abdos pendant toute la montée.",
			"Le ballon roule, il ne glisse pas.",
			"Retour lent : ne t'effondre pas vers la planche.",
		],
		"mistakes": [
			"Descendre les épaules derrière les mains (position cassée).",
			"Creuser le bas du dos au retour.",
			"Monter trop vite avec de l'élan.",
			"Laisser le ballon partir de côté.",
			"Hanches trop basses : c'est un knee tuck, pas un jackknife.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en revenant vers la planche.",
			"concentric": "Expire en montant les hanches vers le plafond.",
		},
		"posterUrl": "/exercises/swiss-ball-jackknife/poster.webp",
		"animationUrl": "/exercises/swiss-ball-jackknife/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-knee-tuck",
		"name": "Knee Tuck sur Swiss Ball",
		"sourceName": "Swiss Ball Knee Tuck",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Obliques",
			"Quadriceps",
			"Épaules",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en position de planche haute, mains sous les épaules, tibias posés sur le ballon.",
			"Corps aligné, serre le ventre et les fessiers pour verrouiller le bassin.",
			"Ramène les genoux vers la poitrine en laissant le ballon rouler sous les tibias.",
			"Monte les hanches au passage des genoux, sans les laisser s'effondrer.",
			"Tends à nouveau les jambes pour revenir en planche, sans creuser le bas du dos.",
		],
		"cues": [
			"Le retour se fait par le bassin : enroule-le vers la poitrine.",
			"Épaules au-dessus des mains, bras fixes.",
			"Évite de laisser le ventre s'affaisser au départ.",
			"Genoux centrés : pas de rotation du bassin.",
			"Contrôle la phase de retour autant que la montée.",
		],
		"mistakes": [
			"Creuser le bas du dos en position de départ.",
			"Monter les fesses très haut sans ramener les genoux (compensation).",
			"Laisser le ballon partir sur le côté.",
			"Descendre les épaules derrière les mains.",
			"Revenir en planche en tombant au lieu de contrôler.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en revenant à la planche.",
			"concentric": "Expire en ramenant les genoux vers la poitrine.",
		},
		"posterUrl": "/exercises/swiss-ball-knee-tuck/poster.webp",
		"animationUrl": "/exercises/swiss-ball-knee-tuck/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-kneeling-rollout",
		"name": "Rollout à genoux sur Swiss Ball",
		"sourceName": "Swiss Ball Kneeling Rollout",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Grand dorsal",
			"Épaules",
			"Érecteurs du rachis",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi à genoux, avant-bras posés sur le ballon, coudes fléchis à 90°.",
			"Corps gainé, bassin légèrement rentré, fessiers serrés.",
			"Fais rouler le ballon vers l'avant en étirant tout le corps.",
			"Descends aussi loin que tu peux SANS creuser le bas du dos.",
			"Tire le ballon vers toi avec les abdos pour revenir au départ.",
		],
		"cues": [
			"Le bassin avance avec le buste : pas de séparation.",
			"Stoppe dès que le bas du dos veut creuser.",
			"Serre les fessiers pendant toute la durée.",
			"Le retour se fait par les abdos, pas par les bras.",
			"Petites amplitudes au début, tu étends progressivement.",
		],
		"mistakes": [
			"Laisser le bas du dos se creuser en s'étirant.",
			"Descendre trop loin et perdre le contrôle.",
			"Pousser le bassin en arrière au retour.",
			"Monter les épaules vers les oreilles.",
			"Retenir sa respiration pendant le mouvement.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en déroulant vers l'avant.",
			"concentric": "Expire en ramenant le ballon vers toi.",
		},
		"posterUrl": "/exercises/swiss-ball-kneeling-rollout/poster.webp",
		"animationUrl": "/exercises/swiss-ball-kneeling-rollout/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-leg-curl",
		"name": "Leg curl sur Swiss Ball",
		"sourceName": "Swiss Ball Leg Curl",
		"muscleGroup": "Ischio-jambiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Mollets",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le dos, les deux talons posés sur le ballon, bras le long du corps.",
			"Monte en pont en poussant les talons, hanches alignées épaules-genoux.",
			"Fléchis les genoux pour enrouler le ballon vers tes fessiers.",
			"Garde le bassin haut et stable pendant toute la flexion.",
			"Retends les jambes en contrôlant le retour du ballon, sans poser le bassin.",
		],
		"cues": [
			"Le bassin reste haut du début à la fin de la série.",
			"Serre les fessiers pour verrouiller la position.",
			"Enroule le ballon avec les talons, pas avec les pointes.",
			"Le ballon roule dans l'axe, ni à gauche ni à droite.",
			"Descente plus lente que la flexion.",
		],
		"mistakes": [
			"Laisser le bassin retomber dès que le ballon roule.",
			"Pousser avec les bras pour s'aider.",
			"Faire des à-coups au lieu d'un mouvement contrôlé.",
			"Laisser le ballon partir de côté.",
			"Creuser le bas du dos pour compenser.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en retendant les jambes.",
			"concentric": "Expire en enroulant le ballon vers les fessiers.",
		},
		"posterUrl": "/exercises/swiss-ball-leg-curl/poster.webp",
		"animationUrl": "/exercises/swiss-ball-leg-curl/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-pike",
		"name": "Pike sur Swiss Ball",
		"sourceName": "Swiss Ball Pike",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Épaules",
			"Grand dorsal",
			"Quadriceps",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en planche haute, mains sous les épaules, tibias sur le ballon.",
			"Corps aligné, ventre et fessiers serrés.",
			"Monte les hanches vers le plafond en laissant le ballon rouler vers les pointes de pieds.",
			"Jambes tendues pendant toute la montée : le corps forme un V inversé.",
			"Redescends en contrôlant jusqu'à la planche de départ.",
		],
		"cues": [
			"Jambes TENDUES : c'est la différence avec le jackknife (genoux fléchis).",
			"Le mouvement part des hanches, pas des bras.",
			"Épaules stables, bras fixes.",
			"Serre les abdos pour piloter la montée.",
			"Retour lent jusqu'à la planche, sans s'effondrer.",
		],
		"mistakes": [
			"Fléchir les genoux (c'est alors un jackknife).",
			"Descendre les épaules derrière les mains.",
			"Creuser le bas du dos au retour.",
			"Ballon qui part de côté.",
			"Montée avec élan, sans contrôle.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en revenant vers la planche.",
			"concentric": "Expire en montant les hanches.",
		},
		"posterUrl": "/exercises/swiss-ball-pike/poster.webp",
		"animationUrl": "/exercises/swiss-ball-pike/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-push-up",
		"name": "Pompes mains sur Swiss Ball",
		"sourceName": "Swiss Ball Push-up (Hands on Ball)",
		"muscleGroup": "Pectoraux",
		"secondaryMuscles": [
			"Triceps",
			"Deltoïde antérieur",
			"Abdominaux",
		],
		"bodyPart": "Haut du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mains posées sur les côtés du ballon, corps en planche, pieds au sol largeur de hanches.",
			"Corps aligné de la tête aux talons, ventre et fessiers serrés.",
			"Descends la poitrine vers le ballon en contrôlant la stabilité des épaules.",
			"Descends jusqu'à ce que la poitrine frôle le ballon.",
			"Pousse pour remonter sans laisser le ballon rouler de côté.",
		],
		"cues": [
			"Serre le ballon entre les mains pour le verrouiller.",
			"Épaules actives, omoplates légèrement serrées.",
			"Corps en planche : bassin ni qui tombe, ni qui monte.",
			"Descends lentement, la stabilité d'abord.",
			"Regard au sol, nuque alignée.",
		],
		"mistakes": [
			"Laisser le ballon rouler vers l'avant ou l'arrière.",
			"Monter les fesses ou laisser le bassin tomber.",
			"Coudes totalement écartés (position d'épaule fragile).",
			"Tête qui plonge avant la poitrine.",
			"Amplitude trop réduite par peur du glissement.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente.",
			"concentric": "Expire en poussant vers le haut.",
		},
		"posterUrl": "/exercises/swiss-ball-push-up/poster.webp",
		"animationUrl": "/exercises/swiss-ball-push-up/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-push-up-feet",
		"name": "Pompes pieds sur Swiss Ball",
		"sourceName": "Swiss Ball Push-up (Feet on Ball)",
		"muscleGroup": "Pectoraux",
		"secondaryMuscles": [
			"Triceps",
			"Deltoïde antérieur",
			"Abdominaux",
		],
		"bodyPart": "Haut du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en planche haute, mains au sol sous les épaules, tibias ou cou-de-pied posés sur le ballon.",
			"Corps aligné de la tête aux talons, serre le ventre et les fessiers.",
			"Descends la poitrine vers le sol, coudes à environ 45° du buste.",
			"Descends jusqu'à ce que la poitrine soit proche du sol, sans laisser le bassin s'affaisser.",
			"Pousse pour remonter en gardant le ballon immobile.",
		],
		"cues": [
			"Le ballon ne doit ni rouler ni bouger latéralement.",
			"Corps gainé comme une planche : aucune flexion des hanches.",
			"Coudes ni totalement écartés ni collés au corps.",
			"Regard au sol, nuque dans l'alignement du dos.",
			"Si le ballon bouge trop, écarte légèrement les pieds.",
		],
		"mistakes": [
			"Laisser le bassin descendre pendant la descente.",
			"Monter les fesses : c'est un pike, plus une pompe.",
			"Descendre trop vite et perdre le contrôle du ballon.",
			"Tête qui rentre entre les épaules.",
			"Amplitude réduite par peur de l'instabilité.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente.",
			"concentric": "Expire en poussant vers le haut.",
		},
		"posterUrl": "/exercises/swiss-ball-push-up-feet/poster.webp",
		"animationUrl": "/exercises/swiss-ball-push-up-feet/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-reverse-hyperextension",
		"name": "Extension de hanche inversée sur Swiss Ball",
		"sourceName": "Swiss Ball Reverse Hyperextension",
		"muscleGroup": "Fessiers",
		"secondaryMuscles": [
			"Ischio-jambiers",
			"Érecteurs du rachis",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Couché sur le ventre, bassin calé sur le sommet du ballon, mains au sol sous les épaules.",
			"Jambes tendues, pointes proches du sol au départ.",
			"Monte les deux jambes en extension de hanche, jusqu'à l'alignement du corps.",
			"Serre les fessiers en haut une seconde, sans cambrer excessivement.",
			"Redescends lentement les jambes vers le sol en contrôlant.",
		],
		"cues": [
			"Le mouvement part des hanches, pas du bas du dos.",
			"Serre le ventre pour protéger les lombaires.",
			"Amplitude confortable : pas besoin de monter très haut.",
			"Jambes tendues mais détendues.",
			"Descente deux fois plus lente que la montée.",
		],
		"mistakes": [
			"Cambrer le bas du dos en cherchant de la hauteur.",
			"Donner de l'élan en rebondissant sur le sol.",
			"Monter une jambe plus haut que l'autre.",
			"Pousser avec les mains pour s'aider.",
			"Descendre trop vite et perdre la tension.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en redescendant les jambes.",
			"concentric": "Expire en montant les jambes et en serrant les fessiers.",
		},
		"posterUrl": "/exercises/swiss-ball-reverse-hyperextension/poster.webp",
		"animationUrl": "/exercises/swiss-ball-reverse-hyperextension/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-side-plank",
		"name": "Side plank sur Swiss Ball",
		"sourceName": "Swiss Ball Side Plank",
		"muscleGroup": "Obliques",
		"secondaryMuscles": [
			"Abdominaux",
			"Moyen fessier",
			"Épaules",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le côté, coude sous l'épaule, les deux pieds posés sur le ballon.",
			"Monte les hanches jusqu'à l'alignement épaules-chevilles.",
			"Serre les obliques et les fessiers pour verrouiller la position.",
			"Épaule active : pousse dans le sol, ne t'affaisse pas.",
			"Tiens la position, puis change de côté.",
		],
		"cues": [
			"Corps en ligne : ni hanches basses, ni fesses en arrière.",
			"Pieds joints ou l'un devant l'autre sur le ballon.",
			"Pousse le ballon légèrement vers le sol pour le contrôler.",
			"Respire calmement, sans lâcher la contraction.",
			"Bras libre le long du corps ou tendu vers le plafond.",
		],
		"mistakes": [
			"Laisser les hanches tomber vers le sol.",
			"Pivoter le buste vers l'avant.",
			"Monter l'épaule vers l'oreille.",
			"Laisser le ballon rouler vers l'avant.",
			"Tenir trop longtemps au prix de l'alignement.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Respiration continue et contrôlée pendant la tenue.",
			"concentric": "Respiration continue et contrôlée pendant la tenue.",
		},
		"posterUrl": "/exercises/swiss-ball-side-plank/poster.webp",
		"animationUrl": "/exercises/swiss-ball-side-plank/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-single-leg-curl",
		"name": "Leg curl unilatéral sur Swiss Ball",
		"sourceName": "Swiss Ball Single Leg Curl",
		"muscleGroup": "Ischio-jambiers",
		"secondaryMuscles": [
			"Grand fessier",
			"Mollets",
			"Abdominaux",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allonge-toi sur le dos, un talon posé au centre du ballon, l'autre jambe tendue en l'air.",
			"Pousse dans le talon pour monter en pont, hanches alignées épaules-genoux.",
			"Fléchis le genou pour enrouler le ballon vers tes fessiers.",
			"Garde le bassin haut pendant toute la flexion.",
			"Retends la jambe en contrôlant le retour du ballon, sans poser le bassin.",
		],
		"cues": [
			"Bassin verrouillé : il ne doit ni tourner ni retomber pendant la flexion.",
			"Pousse le talon dans le ballon pour garder la tension.",
			"La jambe en l'air reste stable, elle ne sert pas de contrepoids.",
			"Flexion complète, retour lent.",
			"Serre les fessiers dès la montée en pont.",
		],
		"mistakes": [
			"Laisser le bassin retomber dès que le genou fléchit.",
			"Pousser avec la pointe des pieds au lieu du talon.",
			"Faire l'exercice trop vite par rebond.",
			"Perdre l'alignement du ballon qui part de côté.",
			"Creuser le bas du dos pour compenser la perte de tension.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en retendant la jambe.",
			"concentric": "Expire en enroulant le ballon vers les fessiers.",
		},
		"posterUrl": "/exercises/swiss-ball-single-leg-curl/poster.webp",
		"animationUrl": "/exercises/swiss-ball-single-leg-curl/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-stir-the-pot",
		"name": "Stir the Pot sur Swiss Ball",
		"sourceName": "Swiss Ball Stir the Pot",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Grand dorsal",
			"Épaules",
			"Érecteurs du rachis",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Mets-toi en planche avant, avant-bras posés sur le ballon, corps aligné de la tête aux talons.",
			"Garde les pieds écartés pour la stabilité et serre abdos et fessiers.",
			"Fais tourner les avant-bras pour dessiner un grand cercle avec le ballon, dans un sens.",
			"Le bassin reste immobile : seul le ballon bouge sous tes avant-bras.",
			"Après quelques cercles, change de sens et garde la même qualité d'exécution.",
		],
		"cues": [
			"Corps rigide : le mouvement vient des épaules et des avant-bras, jamais du bassin.",
			"Cercles lents et grands : la vitesse dégrade la position.",
			"Serre les fessiers pour verrouiller le bassin.",
			"Respire régulièrement, sans relâcher le ventre.",
			"Réduis le diamètre des cercles si le bassin part en rotation.",
		],
		"mistakes": [
			"Laisser le bassin pivoter ou se cambrer pendant les cercles.",
			"Monter les hanches et transformer l'exercice en pike.",
			"Aller trop vite et perdre le contrôle du ballon.",
			"Bloquer la respiration au lieu de rester gainé.",
			"Faire des cercles trop petits en compensant avec les épaules hautes.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire sur la moitié du cercle qui t'éloigne du centre.",
			"concentric": "Expire en ramenant le cercle vers le centre.",
		},
		"posterUrl": "/exercises/swiss-ball-stir-the-pot/poster.webp",
		"animationUrl": "/exercises/swiss-ball-stir-the-pot/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-v-up",
		"name": "V-Up avec Swiss Ball",
		"sourceName": "Swiss Ball V-Up",
		"muscleGroup": "Abdominaux",
		"secondaryMuscles": [
			"Obliques",
			"Quadriceps",
			"Épaules",
		],
		"bodyPart": "Tronc",
		"equipment": "Swiss Ball",
		"instructions": [
			"Allongé sur le dos, ballon serré entre les pieds, bras tendus derrière la tête au sol.",
			"Monte simultanément jambes et buste en formant un V.",
			"Saisis le ballon avec les mains, puis redescends en contrôlant.",
			"Au sol, le ballon passe des mains vers les pieds pour la répétition suivante.",
			"Enchaîne les répétitions en gardant le bas du dos collé au sol.",
		],
		"cues": [
			"Bas du dos collé au sol pendant toute l'amplitude.",
			"Membres tendus : jambes et bras restent droits.",
			"Saisis le ballon avec les mains, ne le lances pas.",
			"Descente lente des membres, sans lâcher la tension.",
			"Respire à chaque transfert.",
		],
		"mistakes": [
			"Décoller le bas du dos du sol.",
			"Genoux fléchis : le V perd sa forme.",
			"Balancer les jambes avec de l'élan.",
			"Lâcher le ballon en plein mouvement.",
			"Descendre trop vite et se laisser tomber.",
		],
		"levels": [
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en redescendant membres et ballon.",
			"concentric": "Expire en montant en V.",
		},
		"posterUrl": "/exercises/swiss-ball-v-up/poster.webp",
		"animationUrl": "/exercises/swiss-ball-v-up/animation.mp4",
	},
	{
		"sourceExerciseId": "swiss-ball-wall-squat",
		"name": "Squat mural avec Swiss Ball",
		"sourceName": "Swiss Ball Wall Squat",
		"muscleGroup": "Quadriceps",
		"secondaryMuscles": [
			"Grand fessier",
			"Ischio-jambiers",
			"Mollets",
		],
		"bodyPart": "Bas du corps",
		"equipment": "Swiss Ball",
		"instructions": [
			"Place le ballon entre le mur et le bas de ton dos, pieds légèrement devant, largeur de hanches.",
			"Appuie-toi dans le ballon et verrouille le gainage.",
			"Descends en squat en laissant le ballon rouler le long du mur, jusqu'à cuisses parallèles au sol.",
			"Garde les genoux dans l'axe des pieds et le poids sur les talons.",
			"Pousse dans le sol pour remonter, sans décoller le dos du ballon.",
		],
		"cues": [
			"Le contact dos-ballon reste constant pendant toute la descente.",
			"Genoux vers l'avant, jamais rentrés vers l'intérieur.",
			"Poids réparti sur tout le pied, talons ancrés.",
			"Regard droit, poitrine ouverte.",
			"Descends lentement, remonte de la même façon.",
		],
		"mistakes": [
			"Décoller le bas du dos du ballon.",
			"Descendre plus bas que son niveau de mobilité.",
			"Laisser les genoux partir vers l'intérieur.",
			"Se servir des mains sur les cuisses pour remonter.",
			"Descendre trop vite en se laissant tomber.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire pendant la descente.",
			"concentric": "Expire en poussant vers le haut.",
		},
		"posterUrl": "/exercises/swiss-ball-wall-squat/poster.webp",
		"animationUrl": "/exercises/swiss-ball-wall-squat/animation.mp4",
	},
	{
		"sourceExerciseId": "wall-slide-mini-band",
		"name": "Wall slide avec mini-bande",
		"sourceName": "Wall Slide with Mini Band",
		"muscleGroup": "Épaules",
		"secondaryMuscles": [
			"Rhomboïdes",
			"Deltoïde postérieur",
			"Coiffe des rotateurs",
		],
		"bodyPart": "Tronc",
		"equipment": "Mini-bande",
		"instructions": [
			"Place-toi face au mur, à un pas de distance, avant-bras posés à hauteur d’épaules.",
			"Mets la mini-bande autour de tes poignets.",
			"Pousse légèrement tes avant-bras dans le mur et tire la bande vers l’extérieur.",
			"Glisse les bras vers le haut le plus loin possible sans décoller les avant-bras ni cambrer.",
			"Redescends lentement au point de départ en gardant la tension sur la bande.",
		],
		"cues": [
			"Avant-bras toujours en contact avec le mur.",
			"Pousse la bande vers l’extérieur pendant toute la montée.",
			"Côtes vers le bas : pas de cambrure du bas du dos.",
			"Descends aussi lentement que tu montes.",
			"Amplitude progressive : va vers le haut sans forcer l’épaule.",
		],
		"mistakes": [
			"Décoller les avant-bras ou les mains du mur.",
			"Cambrer le bas du dos pour monter plus haut.",
			"Relâcher la tension de la bande pendant la descente.",
			"Monter les épaules vers les oreilles.",
			"Aller trop haut trop vite au prix de la position.",
		],
		"levels": [
			"Débutant",
			"Intermédiaire",
			"Avancé",
		],
		"breathing": {
			"eccentric": "Inspire en descendant les bras.",
			"concentric": "Expire en glissant vers le haut.",
		},
		"posterUrl": "/exercises/wall-slide-mini-band/poster.webp",
		"animationUrl": "/exercises/wall-slide-mini-band/animation.mp4",
	}

];
