<script lang="ts">
	/**
	 * Système d'icônes G-FLUX — une seule famille : Lucide (@lucide/svelte).
	 * Toutes les icônes partagent le même stroke, la même logique de couleur
	 * (currentColor) et la même géométrie 24×24.
	 *
	 * Usage :
	 *   <Icon name="flame" size={18} class="text-brand" />
	 *   <Icon name="ruler" size={12} />
	 *
	 * Fallback : si le nom n'existe pas dans le mapping, on n'affiche JAMAIS le
	 * nom technique à l'utilisateur — on ne rend rien et on log en développement.
	 */
	import type { Component } from 'svelte';
	import {
		Activity,
		Apple,
		ArrowDown,
		ArrowLeft,
		ArrowRight,
		ArrowUp,
		ArrowUpRight,
		Award,
		BadgeCheck,
		Banana,
		Banknote,
		Barcode,
		Bell,
		BellOff,
		BellRing,
		Bean,
		Beef,
		Bone,
		Bookmark,
		BookOpen,
		Box,
		Brain,
		Broccoli,
		Cake,
		CakeSlice,
		CalendarCheck,
		CalendarClock,
		CalendarDays,
		CalendarRange,
		CalendarX2,
		Camera,
		Candy,
		Carrot,
		ChartBar,
		ChartColumn,
		ChartLine,
		ChartPie,
		ChartSpline,
		Check,
		ChefHat,
		Cherry,
		ChevronDown,
		ChevronLeft,
		ChevronRight,
		ChevronUp,
		CircleCheck,
		CircleX,
		Citrus,
		ClipboardCheck,
		ClipboardList,
		ClipboardPen,
		Clock,
		Clock3,
		Cloud,
		Coffee,
		Copy,
		Cookie,
		CreditCard,
		Croissant,
		CupSoda,
		Donut,
		Download,
		Droplet,
		Drumstick,
		Dumbbell,
		Egg,
		EggFried,
		ExternalLink,
		Eye,
		EyeOff,
		FileImage,
		FilePlus,
		FileText,
		Fish,
		FishSymbol,
		Flame,
		Flower2,
		Folder,
		FolderOpen,
		Footprints,
		Gauge,
		Gift,
		GlassWater,
		Grape,
		Hamburger,
		Heart,
		HeartPulse,
		Hourglass,
		House,
		IceCreamBowl,
		IceCreamCone,
		Image,
		Images,
		Info,
		Laptop,
		Layers,
		LayoutGrid,
		Leaf,
		LifeBuoy,
		LeafyGreen,
		Lightbulb,
		ListChecks,
		ListTodo,
		Lock,
		LogOut,
		Lollipop,
		Mail,
		MapPin,
		Medal,
		Menu,
		MessageCircle,
		Mic,
		Milk,
		Minus,
		Monitor,
		Moon,
		Music,
		Navigation,
		Notebook,
		NotebookPen,
		Nut,
		Package,
		PanelLeft,
		Paperclip,
		Phone,
		Frown,
		PartyPopper,
		Pause,
		Percent,
		PiggyBank,
		Pizza,
		Play,
		Plus,
		Popcorn,
		Popsicle,
		QrCode,
		RefreshCw,
		Repeat,
		Rocket,
		RotateCcw,
		Rows3,
		Ruler,
		Salad,
		Sandwich,
		Save,
		Scale,
		Scan,
		Search,
		Settings,
		Share,
		ShieldCheck,
		Shirt,
		Shuffle,
		Slice,
		Smartphone,
		Soup,
		Sparkle,
		Sparkles,
		Sprout,
		SquareStack,
		Star,
		Sun,
		Sunrise,
		Target,
		ThumbsUp,
		Timer,
		TimerOff,
		Trash,
		TreePine,
		TrendingUp,
		TriangleAlert,
		Trophy,
		Undo2,
		Upload,
		Users,
		Utensils,
		Video,
		Volume2,
		VolumeX,
		Wallet,
		Watch,
		Wheat,
		Wine,
		Wrench,
		X,
		Zap,
		ZapOff,
	} from '@lucide/svelte';

	const ICONS: Record<string, Component> = {
		// ---- Navigation & app ----
		home: House,
		house: House,
		notebook: Notebook,
		notebookPen: NotebookPen,
		trendingUp: TrendingUp,
		clipboardCheck: ClipboardCheck,
		clipboardList: ClipboardList,
		clipboardPen: ClipboardPen,
		chefHat: ChefHat,
		wrench: Wrench,
		menu: Menu,
		settings: Settings,
		logOut: LogOut,
		layoutGrid: LayoutGrid,
		panelLeft: PanelLeft,
		rows3: Rows3,
		layers: Layers,
		squareStack: SquareStack,
		box: Box,
		package: Package,
		bookOpen: BookOpen,
		cloud: Cloud,
		bookmark: Bookmark,
		mail: Mail,
		lock: Lock,
		shieldCheck: ShieldCheck,
		users: Users,
		user: Users,

		// ---- Graphiques & progression ----
		chartBar: ChartBar,
		chartLine: ChartLine,
		chartColumn: ChartColumn,
		chartPie: ChartPie,
		chartSpline: ChartSpline,
		gauge: Gauge,
		activity: Activity,
		heartPulse: HeartPulse,
		target: Target,
		rocket: Rocket,
		trophy: Trophy,
		medal: Medal,
		award: Award,
		badgeCheck: BadgeCheck,
		sparkles: Sparkles,
		sparkle: Sparkle,
		star: Star,
		thumbsUp: ThumbsUp,
		gift: Gift,
		partyPopper: PartyPopper,

		// ---- Journal — repas ----
		sunrise: Sunrise,
		sun: Sun,
		utensils: Utensils,
		moon: Moon,
		apple: Apple,
		cookie: Cookie,
		copy: Copy,
		flame: Flame,
		wheat: Wheat,
		drumstick: Drumstick,
		droplet: Droplet,
		glassWater: GlassWater,
		cupSoda: CupSoda,
		coffee: Coffee,
		wine: Wine,
		banana: Banana,
		cherry: Cherry,
		grape: Grape,
		citrus: Citrus,
		salad: Salad,
		sandwich: Sandwich,
		soup: Soup,
		hamburger: Hamburger,
		pizza: Pizza,
		croissant: Croissant,
		egg: Egg,
		eggFried: EggFried,
		beef: Beef,
		fish: Fish,
		fishSymbol: FishSymbol,
		milk: Milk,
		nut: Nut,
		bean: Bean,
		broccoli: Broccoli,
		carrot: Carrot,
		leaf: Leaf,
		leafyGreen: LeafyGreen,
		sprout: Sprout,
		popcorn: Popcorn,
		candy: Candy,
		lollipop: Lollipop,
		iceCreamBowl: IceCreamBowl,
		iceCreamCone: IceCreamCone,
		popsicle: Popsicle,
		donut: Donut,
		cake: Cake,
		cakeSlice: CakeSlice,
		slice: Slice,
		bone: Bone,

		// ---- Mesures & photos ----
		ruler: Ruler,
		scale: Scale,
		watch: Watch,
		camera: Camera,
		image: Image,
		images: Images,
		fileImage: FileImage,
		filePlus: FilePlus,
		fileText: FileText,
		shirt: Shirt,
		footprints: Footprints,
		dumbbell: Dumbbell,
		brain: Brain,
		treePine: TreePine,
		flower2: Flower2,

		// ---- Interaction ----
		search: Search,
		x: X,
		barcode: Barcode,
		qrCode: QrCode,
		scan: Scan,
		heart: Heart,
		chevronDown: ChevronDown,
		chevronLeft: ChevronLeft,
		chevronUp: ChevronUp,
		chevronRight: ChevronRight,
		arrowUp: ArrowUp,
		arrowDown: ArrowDown,
		arrowLeft: ArrowLeft,
		arrowRight: ArrowRight,
		arrowUpRight: ArrowUpRight,
		lightbulb: Lightbulb,
		plus: Plus,
		minus: Minus,
		percent: Percent,
		check: Check,
		circleCheck: CircleCheck,
		circleX: CircleX,
		info: Info,
		triangleAlert: TriangleAlert,
		messageCircle: MessageCircle,
		mic: Mic,
		paperclip: Paperclip,
		clock: Clock,
		clock3: Clock3,
		timer: Timer,
		timerOff: TimerOff,
		hourglass: Hourglass,
		calendarDays: CalendarDays,
		calendarCheck: CalendarCheck,
		calendarClock: CalendarClock,
		calendarRange: CalendarRange,
		listChecks: ListChecks,
		listTodo: ListTodo,
		lifeBuoy: LifeBuoy,
		trash: Trash,
		save: Save,
		edit: ClipboardPen,
		pencil: ClipboardPen,
		phone: Phone,
		frown: Frown,
		play: Play,
		pause: Pause,
		video: Video,
		bell: Bell,
		bellRing: BellRing,
		volume2: Volume2,
		volumeX: VolumeX,
		music: Music,
		download: Download,
		upload: Upload,
		share: Share,
		externalLink: ExternalLink,
		refreshCw: RefreshCw,
		undo: Undo2,
		undo2: Undo2,
		repeat: Repeat,
		shuffle: Shuffle,
		rotateCcw: RotateCcw,
		mapPin: MapPin,
		navigation: Navigation,
		smartphone: Smartphone,
		monitor: Monitor,
		laptop: Laptop,
		wallet: Wallet,
		banknote: Banknote,
		creditCard: CreditCard,
		piggyBank: PiggyBank,
		zap: Zap,
		zapOff: ZapOff,
		eye: Eye,
		eyeOff: EyeOff,
		bellOff: BellOff,
		calendarX: CalendarX2,
	};

	let {
		name,
		size = 18,
		strokeWidth = 2,
		class: klass = '',
		...rest
	}: {
		name: string;
		size?: number;
		strokeWidth?: number;
		class?: string;
		[k: string]: unknown;
	} = $props();

	const Comp = $derived(ICONS[name]);

	if (import.meta.env.DEV && !Comp) {
		console.warn(`[Icon] Icône inconnue "${name}" — rien n'est affiché à la place du nom technique.`);
	}
</script>

{#if Comp}
	<svelte:component this={Comp} {size} {strokeWidth} class={klass} {...rest} />
{/if}